name: Build App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
   build_image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Vars
        run: |
         echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          push: true
          build-args: |
            GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}
          tags: ${{ env.IMAGE }}:latest